package com.school.roster.school_roster_backend.entity.enums;

public enum Position {
    TEACHER_I,
    TEACHER_II,
    TEACHER_III,
    MASTER_TEACHER_I,
    MASTER_TEACHER_II,
    MASTER_TEACHER_III,
    MASTER_TEACHER_IV,
    HEAD_TEACHER_I,
    HEAD_TEACHER_II,
    HEAD_TEACHER_III,
    HEAD_TEACHER_IV,
    HEAD_TEACHER_V,
    HEAD_TEACHER_VI,
    ASST_SCHOOL_PRINCIPAL_I,
    ASST_SCHOOL_PRINCIPAL_II,
    ASST_SCHOOL_PRINCIPAL_III,
    SCHOOL_PRINCIPAL_I,
    SCHOOL_PRINCIPAL_II,
    SCHOOL_PRINCIPAL_III,
    SCHOOL_PRINCIPAL_IV
}
