/* eslint-disable @typescript-eslint/no-duplicate-enum-values */
// src/components/profile/enums.ts

// Mirrors your backend enum definitions

// From Position.java
export enum Position {
  TEACHER_I = 'TEACHER_I',
  TEACHER_II = 'TEACHER_II',
  TEACHER_III = 'TEACHER_III',
  MASTER_TEACHER_I = 'MASTER_TEACHER_I',
  MASTER_TEACHER_II = 'MASTER_TEACHER_II',
  MASTER_TEACHER_III = 'MASTER_TEACHER_III',
  MASTER_TEACHER_IV = 'MASTER_TEACHER_IV',
  HEAD_TEACHER_I = 'HEAD_TEACHER_I',
  HEAD_TEACHER_II = 'HEAD_TEACHER_II',
  HEAD_TEACHER_III = 'HEAD_TEACHER_III',
  HEAD_TEACHER_IV = 'HEAD_TEACHER_IV',
  HEAD_TEACHER_V = 'HEAD_TEACHER_V',
  HEAD_TEACHER_VI = 'HEAD_TEACHER_VI',
  ASST_SCHOOL_PRINCIPAL_I = 'ASST_SCHOOL_PRINCIPAL_I',
  ASST_SCHOOL_PRINCIPAL_II = 'ASST_SCHOOL_PRINCIPAL_II',
  ASST_SCHOOL_PRINCIPAL_III = 'ASST_SCHOOL_PRINCIPAL_III',
  SCHOOL_PRINCIPAL_I = 'SCHOOL_PRINCIPAL_I',
  SCHOOL_PRINCIPAL_II = 'SCHOOL_PRINCIPAL_II',
  SCHOOL_PRINCIPAL_III = 'SCHOOL_PRINCIPAL_III',
  SCHOOL_PRINCIPAL_IV = 'SCHOOL_PRINCIPAL_IV',
}

// From Role.java
export enum Role {
  STUDENT = 'STUDENT',
  TEACHER = 'TEACHER',
  TEACHER_LEAD = 'TEACHER_LEAD',
  OFFICE_ADMINISTRATOR = 'OFFICE_ADMINISTRATOR',
  ADMINISTRATOR = 'ADMINISTRATOR',
  ADMIN = 'ADMIN',
}

// From SalaryGrade.java (maps to the numeric grade code)
export enum SalaryGrade {
  TEACHER_I = 11,
  TEACHER_II = 12,
  TEACHER_III = 13,
  MASTER_TEACHER_I = 18,
  MASTER_TEACHER_II = 19,
  MASTER_TEACHER_III = 20,
  MASTER_TEACHER_IV = 21,
  HEAD_TEACHER_I = 14,
  HEAD_TEACHER_II = 15,
  HEAD_TEACHER_III = 16,
  HEAD_TEACHER_IV = 17,
  HEAD_TEACHER_V = 18,
  HEAD_TEACHER_VI = 19,
  ASST_SCHOOL_PRINCIPAL_I = 18,
  ASST_SCHOOL_PRINCIPAL_II = 19,
  ASST_SCHOOL_PRINCIPAL_III = 20,
  SCHOOL_PRINCIPAL_I = 19,
  SCHOOL_PRINCIPAL_II = 20,
  SCHOOL_PRINCIPAL_III = 21,
  SCHOOL_PRINCIPAL_IV = 22,
}

// From StudentGradeStatus.java
export enum StudentGradeStatus {
  FAILED = 'FAILED',
  PASSED = 'PASSED',
  WITH_HONORS = 'WITH_HONORS',
  WITH_HIGH_HONORS = 'WITH_HIGH_HONORS',
  WITH_HIGHEST_HONORS = 'WITH_HIGHEST_HONORS',
}

// From AppointmentType.java
export enum AppointmentType {
  ORIGINAL_APPOINTMENT = 'ORIGINAL_APPOINTMENT',
  SECOND_APPOINTMENT = 'SECOND_APPOINTMENT',
  THIRD_APPOINTMENT = 'THIRD_APPOINTMENT',
  FOURTH_APPOINTMENT = 'FOURTH_APPOINTMENT',
  FIFTH_APPOINTMENT = 'FIFTH_APPOINTMENT',
  SIXTH_APPOINTMENT = 'SIXTH_APPOINTMENT',
  SEVENTH_APPOINTMENT = 'SEVENTH_APPOINTMENT',
  EIGHTH_APPOINTMENT = 'EIGHTH_APPOINTMENT',
  NINTH_APPOINTMENT = 'NINTH_APPOINTMENT',
  TENTH_APPOINTMENT = 'TENTH_APPOINTMENT',
}

// From BMICategory.java
export enum BMICategory {
  SEVERELY_WASTED = 'SEVERELY_WASTED',
  WASTED = 'WASTED',
  NORMAL = 'NORMAL',
  OVERWEIGHT = 'OVERWEIGHT',
  OBESE = 'OBESE',
}

// From CivilStatus.java
export enum CivilStatus {
  SINGLE = 'SINGLE',
  MARRIED = 'MARRIED',
  WIDOWED = 'WIDOWED',
  DIVORCED = 'DIVORCED',
}

// From PhoneType.java
export enum PhoneType {
  HOME = 'HOME',
  CELLULAR = 'CELLULAR',
  WORK = 'WORK',
}
